name:                tripwire
version:             0.1.0.0
github:              "Innf107/tripwire"
license:             BSD3
author:              "Finn Schneider"
maintainer:          "finn@famschneider.info"
copyright:           "2019 "

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/Innf107/tripwire#readme>

dependencies:
- base >= 4.7 && < 5
- mcrcon
- relude
- lens
- cereal
- clock
- process
- unliftio
- connection
- random
- bytestring
- text
- aeson
- req
- directory
- filepath
- template-haskell
- modern-uri

library:
  source-dirs: src

executables:
  tripwire:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tripwire
    - optparse-applicative

tests:
  tripwire-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tripwire

default-extensions:
  - NoImplicitPrelude
  - ApplicativeDo
  - LambdaCase
  - OverloadedStrings
  - DataKinds
  - TypeFamilies
  - TypeFamilyDependencies
  - FlexibleInstances
  - FlexibleContexts
  - RankNTypes
  - MultiParamTypeClasses
  - PatternSynonyms
  - StandaloneDeriving
  - StandaloneKindSignatures
  - GADTs
  - ConstraintKinds
  - ScopedTypeVariables
  - BlockArguments
  - TypeOperators
  - NamedFieldPuns
  - MultiWayIf
  - PostfixOperators
  - KindSignatures
  - TypeApplications
  - PolyKinds
  - ViewPatterns
  - TupleSections
  - DisambiguateRecordFields
  - ImportQualifiedPost
  - NegativeLiterals
  - DeriveGeneric
  - DeriveDataTypeable
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - EmptyDataDeriving
  - RecordWildCards
  - FunctionalDependencies
  - NumericUnderscores
  - NumDecimals
  - RoleAnnotations
  - QuantifiedConstraints

